blank_issues_enabled: false
contact_links:
  - name: Transparency.dev Slack
    url: https://join.slack.com/t/transparency-dev/shared_invite/zt-27pkqo21d-okUFhur7YZ0rFoJVIOPznQ
    about: Also consider our Slack channel. It's the quickest way to have a conversation with the developers!
